### ISSUE TITLE
Argo Rollouts {{args.property}} Syntax Does Not Work with ResourceOperation/MultiResourceOperation

### ISSUE THREAD

**Issue by danielhelfand** [keikoproj/kubedog#60]
As noted in #58, [kubedog's use of `text/template`](https://github.com/keikoproj/kubedog/blob/d84d16037d4b782556bac7f3102da6bebffee4a7/internal/utilities/util.go#L123) library for parsing resources from yaml files can lead to the following error when working with Argo Rollouts resources:

```
template: Resource:31: function "args" not defined
```

Argo Rollout resources like AnalysisTemplates feature an `{{args.property}}` [parameter syntax](https://argoproj.github.io/argo-rollouts/features/analysis/#analysis-template-arguments) that conflicts with text/templates interpretation of `{{}}`. [text/template interprets this syntax to mean a function](https://cs.opensource.google/go/go/+/master:src/text/template/parse/parse.go;l=765) to be executed as part of making use of a template. Since the function does not exist in this case, the error above occurs. 

The workaround in #58 works if manifests are defined in advance for tests, but if you need to generate manifests as part of a test, it would be very difficult to add in the workaround for each use of `{{args.property}}` that is defined in an analysis template. 

kubedog should amend it's use of templating to support this Argo Rollout syntax. One possible solution to this would be to not template values if no templating values are passed in. 

This can be reproduced using same steps mentioned in #58.

**Comment by garomonegro** [comment]
This is a simple fix. All we need to do is modify `GetResourceFromString` function such that i only uses templating is `args` is not `nil`.

https://github.com/keikoproj/kubedog/blob/d84d16037d4b782556bac7f3102da6bebffee4a7/internal/utilities/util.go#L120-L142

**Comment by danielhelfand** [comment]
Closing this issue. For case of wanting to use templating with these resources, see solution outlined in #58.
